### ISSUE TITLE
Platform error sensor.dewpoint - Integration 'dewpoint' not found.

### ISSUE THREAD

**Issue by eingemaischt** [miguelangel-nubla/home-assistant-dewpoint#8]
I installed it manually - and then with HACS, but in both cases I am not allowed to restart the core due to the error message in the title.

My configuration.yaml:

```
sensor:
  - platform: local_luftdaten
    host: xxx
    name: Luftsensor Einfahrt
    monitored_conditions:
      - SDS_P1
      - SDS_P2
      - BME280_temperature
      - BME280_pressure
      - BME280_humidity
      - signal
  - platform: dewpoint
    sensors:
      dewpoint_abluft:
        friendly_name: "Abluft Taupunkt"
        temperature: sensor.abluft_temperature
        rel_hum: sensor.abluft_humidity
      dewpoint_zuluft:
        friendly_name: "Zuluft Taupunkt"
        temperature: sensor.zuluft_temperature
        rel_hum: sensor.zuluft_humidity
      dewpoint_aussenluft:
        friendly_name: "Aussenlust Taupunkt"
        temperature: sensor.aussenluft_temperature
        rel_hum: sensor.aussenluft_humidity
```
